CREATE SCHEMA IF NOT EXISTS pharmacy;

CREATE TABLE pharmacy.drugs (
                                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                code VARCHAR(100),
                                name VARCHAR(255),
                                dose VARCHAR(100),
                                form VARCHAR(100),
                                manufacturer VARCHAR(255),
                                available_units INT,
                                price DOUBLE
);

insert into pharmacy.drugs values (6,'dd', 'gg', 'ww', '33', 'rgeg', 5, 8.0);
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

INSERT INTO users (username, password)
VALUES ('admin', 'admin123');

CREATE TABLE pharmacy.drugs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(255),
    name            VARCHAR(255),
    dose            VARCHAR(255),
    form            VARCHAR(255),
    manufacturer    VARCHAR(255),
    available_units INT,
    price           DOUBLE PRECISION,
    CONSTRAINT pk_drugs PRIMARY KEY (id)
);